# Generated by Django 4.2.2 on 2024-07-01 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_user_wallet_address_eth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key_eth',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^0[xX][0-9a-fA-F]{64}$', 'The field must be a 64-character hexadecimal address')], verbose_name='Ethereum wallet private key'),
        ),
    ]
